# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: erc20indexer
description: ERC-20 indexer
contracts:
  - name: ERC20
    events:
      - event: "Approval(address indexed owner, address indexed spender, uint256 value)"
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
chains:
  - id: 80094 # Berachain mainnet
    start_block: 0
    contracts:
      - name: ERC20
        address: "0x2f6f07cdcf3588944bf4c42ac74ff24bf56e7590" # WETH
