/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGelatoVRFConsumer,
  IGelatoVRFConsumerInterface,
} from "../IGelatoVRFConsumer";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "round",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "RequestedRandomness",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "randomness",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "fulfillRandomness",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGelatoVRFConsumer__factory {
  static readonly abi = _abi;
  static createInterface(): IGelatoVRFConsumerInterface {
    return new Interface(_abi) as IGelatoVRFConsumerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGelatoVRFConsumer {
    return new Contract(address, _abi, runner) as unknown as IGelatoVRFConsumer;
  }
}
