/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "GelatoVRFConsumerBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GelatoVRFConsumerBase__factory>;
    getContractFactory(
      name: "IGelatoVRFConsumer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGelatoVRFConsumer__factory>;
    getContractFactory(
      name: "SimpleVRFContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SimpleVRFContract__factory>;

    getContractAt(
      name: "GelatoVRFConsumerBase",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.GelatoVRFConsumerBase>;
    getContractAt(
      name: "IGelatoVRFConsumer",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IGelatoVRFConsumer>;
    getContractAt(
      name: "SimpleVRFContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SimpleVRFContract>;

    deployContract(
      name: "GelatoVRFConsumerBase",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GelatoVRFConsumerBase>;
    deployContract(
      name: "IGelatoVRFConsumer",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGelatoVRFConsumer>;
    deployContract(
      name: "SimpleVRFContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SimpleVRFContract>;

    deployContract(
      name: "GelatoVRFConsumerBase",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GelatoVRFConsumerBase>;
    deployContract(
      name: "IGelatoVRFConsumer",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGelatoVRFConsumer>;
    deployContract(
      name: "SimpleVRFContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SimpleVRFContract>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
