FROM ubuntu:24.04                       

ARG CHAIN_SPEC
ARG CUSTOM_BIN_BEACOND
ENV CHAIN_SPEC=${CHAIN_SPEC}

COPY ${CUSTOM_BIN_BEACOND} /tmp/beacond-custom

RUN apt-get update && apt-get install -y curl wget;

RUN echo "Using custom beacond binary ${CUSTOM_BIN_BEACOND}"; \
    cp /tmp/beacond-custom ./beacond; \
    chmod +x beacond;  \
    ./beacond version; \
    sleep 3;
