FROM ubuntu:24.04                       

ARG CHAIN_SPEC
ENV CHAIN_SPEC=${CHAIN_SPEC}

# Install dependencies
RUN apt-get update && apt-get install -y curl wget;

# Download and install beacond
RUN if [ "$TARGETARCH" = "arm64" ]; then \
        ARCH="arm64"; \
    else \
        ARCH="amd64"; \
    fi && \
    if [ "$TARGETOS" = "darwin" ]; then \
        OS="darwin"; \
    else \
        OS="linux"; \
    fi && \
    echo "Using architecture: $ARCH, OS: $OS" && \
    BEACOND_RELEASE_URL=$(curl -s https://api.github.com/repos/berachain/beacon-kit/releases/latest | \
    grep '"browser_download_url":' | \
    sed 's/.*"browser_download_url": "\(.*\)".*/\1/' | \
    grep "beacond-.*-${OS}-${ARCH}.tar.gz" | \
    grep -v "\.sig$"); \
    echo "Downloading beacond from: $BEACOND_RELEASE_URL"; \
    wget $BEACOND_RELEASE_URL; \
    tar -xzf beacond-*.tar.gz; \
    rm beacond-v*.tar.gz; \
    mv ./beacond-v* ./beacond; \
    chmod +x ./beacond; \
    ./beacond version > /dev/null 2>&1

# Set the entrypoint
ENTRYPOINT ["./beacond"]

