FROM ubuntu:24.04                       

ARG CHAIN_SPEC
ARG CUSTOM_BIN_BEACOND
ENV CHAIN_SPEC=${CHAIN_SPEC}

RUN ARCH=$(uname -m) && \
    if [ "$ARCH" != "aarch64" ]; then \
        echo "This image only supports aarch64 (got $ARCH)"; \
        exit 1; \
    fi

COPY ${CUSTOM_BIN_BEACOND} /tmp/beacond-custom

RUN apt-get update && apt-get install -y curl wget;

RUN echo "Using custom beacond binary ${CUSTOM_BIN_BEACOND}"; \
    cp /tmp/beacond-custom ./beacond; \
    chmod +x beacond;  \
    ./beacond version; \
    sleep 3;
