FROM ubuntu:24.04                       

ARG CHAIN_SPEC
ARG CUSTOM_BIN_BEACOND
ENV CHAIN_SPEC=${CHAIN_SPEC}

RUN ARCH=$(uname -m) && \
    if [ "$ARCH" != "aarch64" ]; then \
        echo "This image only supports aarch64 (got $ARCH)"; \
        exit 1; \
    fi

COPY ${CUSTOM_BIN_BEACOND} /tmp/beacond-custom

RUN echo "Using custom beacond binary from /tmp/beacond-custom"; \
    cp /tmp/beacond-custom ./beacond; \
    chmod +x beacond; \
    echo "Custom beacond version:"; \
    ./beacond version; \
    sleep 6;
