[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
bepolia = "http://192.168.2.69:41003/"

[etherscan]
bepolia = { url = "https://testnet.berascan.com/api", key = "14UI273T7YQZUTF6GQG6VWB4WB4F11I815" }
