{
 "title": "Berachain Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "UP/DOWN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "System Infrastructure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{device=\"sdc\"}[1m])/60",
     "legendFormat": "{{device}} writes"
    },
    {
     "expr": "rate(node_disk_reads_completed_total{device=\"sdc\"}[1m])",
     "legendFormat": "{{device}} reads"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(mode) (rate(node_cpu_seconds_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Throughput [1m]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"sdc\"}[1m])/60",
     "legendFormat": "{{device}} reads"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"sdc\"}[1m])",
     "legendFormat": "{{device}} writes"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_Active_bytes", "legendFormat": "active" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "free" },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "cached" }
   ]
  },
  { "title": "beacond", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Consensus Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cometbft_consensus_height", "legendFormat": "{{chain_id}}" }
   ]
  },
  {
   "title": "CometBFT Send/Receive",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(cometbft_p2p_message_receive_bytes_total{__ignore_usage__=\"\"}[$__rate_interval]) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Beacond Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "beacond_node_runtime_alloc_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CometBFT Peers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "targets": [
    { "expr": "cometbft_p2p_peers", "legendFormat": "{{chain_id}}" }
   ]
  },
  { "title": "reth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Reth Block Height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reth_sync_checkpoint", "legendFormat": "{{stage}}" }
   ]
  },
  {
   "title": "Reth Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "reth_network_outgoing_connections",
     "legendFormat": "outgoing"
    },
    {
     "expr": "reth_network_incoming_connections",
     "legendFormat": "incoming"
    }
   ]
  },
  {
   "title": "Reth Txpool",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "reth_transaction_pool_queued_pool_transactions",
     "legendFormat": "queued"
    },
    {
     "expr": "reth_transaction_pool_pending_pool_transactions",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Reth Execution Gas/Sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "flops" } },
   "targets": [
    {
     "expr": "reth_sync_execution_gas_per_second",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "geth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Geth Chain Head",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chain_head_header", "legendFormat": "header" },
    { "expr": "chain_head_receipt", "legendFormat": "receipt" },
    { "expr": "chain_head_finalized", "legendFormat": "finalized" }
   ]
  },
  {
   "title": "Chain Storage Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eth_db_chaindata_disk_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Geth Peers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "targets": [
    { "expr": "p2p_peers_inbound", "legendFormat": "inbound" },
    { "expr": "p2p_peers_outbound", "legendFormat": "outbound" }
   ]
  },
  {
   "title": "Geth Transaction Pool",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 42 },
   "targets": [
    { "expr": "txpool_pending", "legendFormat": "pending" },
    { "expr": "txpool_queued", "legendFormat": "queued" }
   ]
  }
 ]
}