FROM ubuntu:24.04

ARG CUSTOM_BIN_RETH

# Check if the architecture is supported
RUN ARCH=$(uname -m) && \
    if [ "$ARCH" != "aarch64" ]; then \
        echo "This image only supports aarch64 (got $ARCH)"; \
        exit 1; \
    fi

# Copy custom reth binary
COPY ${CUSTOM_BIN_RETH} /tmp/reth-custom

# Install dependencies
RUN apt-get update && apt-get install -y curl wget;

# Use custom reth binary
RUN echo "Using custom reth binary ${CUSTOM_BIN_RETH}"; \
    cp /tmp/reth-custom /usr/local/bin/reth; \
    chmod +x /usr/local/bin/reth; \
    reth --version; \
    sleep 3; 